export default function getAllProducts() {
  return [
    {
      id: 'Cozy Dreams',
      slug: 'cozy-dreams',
      name: "Cozy Dreams",
      category: 'Bedroom',
      price: 500_000,
      stock: 15,
      imageUrl: '/assets/images/bedroom.jpg',
      description: `Transform your bedroom into a cozy haven with our Cozy Dreams comforter set. Made from high-quality fabric, this bedding offers unmatched softness and warmth, ensuring a restful sleep experience.`,
    },
    {
      id: 'Elegant Glow Lamp',
      slug: 'elegant-glow-lamp',
      name: "Elegant Glow Lamp",
      category: 'Living Room',
      price: 300_000,
      stock: 8,
      imageUrl: '/assets/images/lampu.jpg',
      description: `This elegant table lamp adds a warm and inviting ambiance to your living room. With its sleek design and soft lighting, it perfectly complements any modern interior style.`,
    },
    {
      id: 'Modern Coffee Table',
      slug: 'modern-coffee-table',
      name: "Modern Coffee Table",
      category: 'Living Room',
      price: 750_000,
      stock: 5,
      imageUrl: '/assets/images/meja kopi.jpg',
      description: `A stylish and functional addition to your living room, this modern coffee table features a durable surface and ample storage space for magazines, remote controls, and more.`,
    },
    {
      id: 'Serenity Curtains',
      slug: 'serenity-curtains',
      name: "Serenity Curtains",
      category: 'Bedroom',
      price: 250_000,
      stock: 20,
      imageUrl: '/assets/images/horden.jpg',
      description: `Elevate the elegance of your bedroom with our Serenity Curtains. Made from premium fabric, these curtains block out light effectively while adding a touch of sophistication to your space.`,
    },
    {
      id: 'Comfy Sofa Set',
      slug: 'comfy-sofa-set',
      name: "Comfy Sofa Set",
      category: 'Living Room',
      price: 5_000_000,
      stock: 3,
      imageUrl: '/assets/images/sofa.jpg',
      description: `Upgrade your living room with this ultra-comfortable sofa set, featuring a plush design and ample seating space for family and friends.`,
    },
    {
      id: 'Artistic Wall Frame',
      slug: 'artistic-wall-frame',
      name: "Artistic Wall Frame",
      category: 'Living Room',
      price: 150_000,
      stock: 25,
      imageUrl: '/assets/images/wall.jpg',
      description: `Add a touch of art to your living room with this artistic wall frame. The minimalist yet elegant design fits perfectly with both modern and classic decor.`,
    },
    {
      id: 'Cloud Soft Rug',
      slug: 'cloud-soft-rug',
      name: "Cloud Soft Rug",
      category: 'Bedroom',
      price: 350_000,
      stock: 10,
      imageUrl: '/assets/images/karpet.jpg',
      description: `Step onto luxury with our Cloud Soft Rug. Designed for ultimate comfort, this rug provides a cozy and warm feel underfoot while adding style to your bedroom.`,
    },

    {
      id: 'Ceramic Kitchen Set',
      slug: 'ceramic-kitchen-set',
      name: "Ceramic Kitchen Set",
      category: 'Kitchen',
      price: 450_000,
      stock: 15,
      imageUrl: '/assets/images/ceramic.jpg',
      description: `Upgrade your kitchen with our premium Ceramic Kitchen Set. Perfect for cooking and serving, this durable and stylish set is an essential addition to your home.`,
    },
    {
      id: 'Stainless Steel Utensils',
      slug: 'stainless-steel-utensils',
      name: "Stainless Steel Utensils",
      category: 'Kitchen',
      price: 150_000,
      stock: 30,
      imageUrl: '/assets/images/spoon.jpg',
      description: `Experience durability and elegance with our Stainless Steel Utensils. Ideal for everyday use, these utensils are designed for convenience and style.`,
    }
    
  ];
}
